# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bmodel.proto\"\\\n\x10NormalizerConfig\x12\r\n\x05lower\x18\x01 \x01(\x08\x12\x16\n\x0eunicode_format\x18\x02 \x01(\t\x12!\n\x0c\x63ustom_rules\x18\x03 \x03(\x0b\x32\x0b.CustomRule\"2\n\nCustomRule\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12\x13\n\x0breplacement\x18\x02 \x01(\t\"\x8e\x01\n\rUnigramConfig\x12\x12\n\nvocab_seed\x18\x01 \x01(\r\x12\x13\n\x0bmax_sub_len\x18\x02 \x01(\r\x12\x10\n\x08\x65m_iters\x18\x03 \x01(\r\x12\r\n\x05n_per\x18\x04 \x01(\x02\x12\x0f\n\x07\x65psilon\x18\x05 \x01(\x02\x12\r\n\x05\x61lpha\x18\x06 \x01(\x02\x12\x13\n\x0bunk_penalty\x18\x07 \x01(\x02\"*\n\x0bUnigramProb\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04prob\x18\x02 \x01(\x02\"(\n\nVocabEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r\"#\n\x03UNK\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r\"#\n\x03PAD\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r\"#\n\x03SOS\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r\"#\n\x03\x45OS\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r\"a\n\x13\x44\x65\x66\x61ultSpecialToken\x12\x11\n\x03pad\x18\x01 \x01(\x0b\x32\x04.PAD\x12\x11\n\x03unk\x18\x02 \x01(\x0b\x32\x04.UNK\x12\x11\n\x03sos\x18\x03 \x01(\x0b\x32\x04.SOS\x12\x11\n\x03\x65os\x18\x04 \x01(\x0b\x32\x04.EOS\"3\n\x10\x43ustomTokenEntry\x12\x10\n\x08sp_token\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r\"\x94\x02\n\nModelProto\x12\x1a\n\x05vocab\x18\x01 \x03(\x0b\x32\x0b.VocabEntry\x12,\n\x0especial_tokens\x18\x02 \x01(\x0b\x32\x14.DefaultSpecialToken\x12(\n\rcustom_tokens\x18\x03 \x03(\x0b\x32\x11.CustomTokenEntry\x12%\n\nnormalizer\x18\x04 \x01(\x0b\x32\x11.NormalizerConfig\x12\x12\n\nmodel_type\x18\x05 \x01(\t\x12\x12\n\nvocab_size\x18\x06 \x01(\r\x12\x1f\n\x07unigram\x18\x07 \x01(\x0b\x32\x0e.UnigramConfig\x12\"\n\x0cunigram_prob\x18\x08 \x03(\x0b\x32\x0c.UnigramProbb\x06proto3')
)




_NORMALIZERCONFIG = _descriptor.Descriptor(
  name='NormalizerConfig',
  full_name='NormalizerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lower', full_name='NormalizerConfig.lower', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unicode_format', full_name='NormalizerConfig.unicode_format', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_rules', full_name='NormalizerConfig.custom_rules', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=107,
)


_CUSTOMRULE = _descriptor.Descriptor(
  name='CustomRule',
  full_name='CustomRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pattern', full_name='CustomRule.pattern', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='replacement', full_name='CustomRule.replacement', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=159,
)


_UNIGRAMCONFIG = _descriptor.Descriptor(
  name='UnigramConfig',
  full_name='UnigramConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vocab_seed', full_name='UnigramConfig.vocab_seed', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_sub_len', full_name='UnigramConfig.max_sub_len', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='em_iters', full_name='UnigramConfig.em_iters', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_per', full_name='UnigramConfig.n_per', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epsilon', full_name='UnigramConfig.epsilon', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='UnigramConfig.alpha', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unk_penalty', full_name='UnigramConfig.unk_penalty', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=304,
)


_UNIGRAMPROB = _descriptor.Descriptor(
  name='UnigramProb',
  full_name='UnigramProb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='UnigramProb.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prob', full_name='UnigramProb.prob', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=348,
)


_VOCABENTRY = _descriptor.Descriptor(
  name='VocabEntry',
  full_name='VocabEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='VocabEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='VocabEntry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=390,
)


_UNK = _descriptor.Descriptor(
  name='UNK',
  full_name='UNK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='UNK.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='UNK.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=427,
)


_PAD = _descriptor.Descriptor(
  name='PAD',
  full_name='PAD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='PAD.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='PAD.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=464,
)


_SOS = _descriptor.Descriptor(
  name='SOS',
  full_name='SOS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='SOS.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='SOS.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=466,
  serialized_end=501,
)


_EOS = _descriptor.Descriptor(
  name='EOS',
  full_name='EOS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='EOS.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='EOS.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=538,
)


_DEFAULTSPECIALTOKEN = _descriptor.Descriptor(
  name='DefaultSpecialToken',
  full_name='DefaultSpecialToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pad', full_name='DefaultSpecialToken.pad', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unk', full_name='DefaultSpecialToken.unk', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sos', full_name='DefaultSpecialToken.sos', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eos', full_name='DefaultSpecialToken.eos', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=637,
)


_CUSTOMTOKENENTRY = _descriptor.Descriptor(
  name='CustomTokenEntry',
  full_name='CustomTokenEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sp_token', full_name='CustomTokenEntry.sp_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='CustomTokenEntry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=639,
  serialized_end=690,
)


_MODELPROTO = _descriptor.Descriptor(
  name='ModelProto',
  full_name='ModelProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vocab', full_name='ModelProto.vocab', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='special_tokens', full_name='ModelProto.special_tokens', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_tokens', full_name='ModelProto.custom_tokens', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normalizer', full_name='ModelProto.normalizer', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_type', full_name='ModelProto.model_type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vocab_size', full_name='ModelProto.vocab_size', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unigram', full_name='ModelProto.unigram', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unigram_prob', full_name='ModelProto.unigram_prob', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=693,
  serialized_end=969,
)

_NORMALIZERCONFIG.fields_by_name['custom_rules'].message_type = _CUSTOMRULE
_DEFAULTSPECIALTOKEN.fields_by_name['pad'].message_type = _PAD
_DEFAULTSPECIALTOKEN.fields_by_name['unk'].message_type = _UNK
_DEFAULTSPECIALTOKEN.fields_by_name['sos'].message_type = _SOS
_DEFAULTSPECIALTOKEN.fields_by_name['eos'].message_type = _EOS
_MODELPROTO.fields_by_name['vocab'].message_type = _VOCABENTRY
_MODELPROTO.fields_by_name['special_tokens'].message_type = _DEFAULTSPECIALTOKEN
_MODELPROTO.fields_by_name['custom_tokens'].message_type = _CUSTOMTOKENENTRY
_MODELPROTO.fields_by_name['normalizer'].message_type = _NORMALIZERCONFIG
_MODELPROTO.fields_by_name['unigram'].message_type = _UNIGRAMCONFIG
_MODELPROTO.fields_by_name['unigram_prob'].message_type = _UNIGRAMPROB
DESCRIPTOR.message_types_by_name['NormalizerConfig'] = _NORMALIZERCONFIG
DESCRIPTOR.message_types_by_name['CustomRule'] = _CUSTOMRULE
DESCRIPTOR.message_types_by_name['UnigramConfig'] = _UNIGRAMCONFIG
DESCRIPTOR.message_types_by_name['UnigramProb'] = _UNIGRAMPROB
DESCRIPTOR.message_types_by_name['VocabEntry'] = _VOCABENTRY
DESCRIPTOR.message_types_by_name['UNK'] = _UNK
DESCRIPTOR.message_types_by_name['PAD'] = _PAD
DESCRIPTOR.message_types_by_name['SOS'] = _SOS
DESCRIPTOR.message_types_by_name['EOS'] = _EOS
DESCRIPTOR.message_types_by_name['DefaultSpecialToken'] = _DEFAULTSPECIALTOKEN
DESCRIPTOR.message_types_by_name['CustomTokenEntry'] = _CUSTOMTOKENENTRY
DESCRIPTOR.message_types_by_name['ModelProto'] = _MODELPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NormalizerConfig = _reflection.GeneratedProtocolMessageType('NormalizerConfig', (_message.Message,), dict(
  DESCRIPTOR = _NORMALIZERCONFIG,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:NormalizerConfig)
  ))
_sym_db.RegisterMessage(NormalizerConfig)

CustomRule = _reflection.GeneratedProtocolMessageType('CustomRule', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMRULE,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:CustomRule)
  ))
_sym_db.RegisterMessage(CustomRule)

UnigramConfig = _reflection.GeneratedProtocolMessageType('UnigramConfig', (_message.Message,), dict(
  DESCRIPTOR = _UNIGRAMCONFIG,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:UnigramConfig)
  ))
_sym_db.RegisterMessage(UnigramConfig)

UnigramProb = _reflection.GeneratedProtocolMessageType('UnigramProb', (_message.Message,), dict(
  DESCRIPTOR = _UNIGRAMPROB,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:UnigramProb)
  ))
_sym_db.RegisterMessage(UnigramProb)

VocabEntry = _reflection.GeneratedProtocolMessageType('VocabEntry', (_message.Message,), dict(
  DESCRIPTOR = _VOCABENTRY,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:VocabEntry)
  ))
_sym_db.RegisterMessage(VocabEntry)

UNK = _reflection.GeneratedProtocolMessageType('UNK', (_message.Message,), dict(
  DESCRIPTOR = _UNK,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:UNK)
  ))
_sym_db.RegisterMessage(UNK)

PAD = _reflection.GeneratedProtocolMessageType('PAD', (_message.Message,), dict(
  DESCRIPTOR = _PAD,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:PAD)
  ))
_sym_db.RegisterMessage(PAD)

SOS = _reflection.GeneratedProtocolMessageType('SOS', (_message.Message,), dict(
  DESCRIPTOR = _SOS,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:SOS)
  ))
_sym_db.RegisterMessage(SOS)

EOS = _reflection.GeneratedProtocolMessageType('EOS', (_message.Message,), dict(
  DESCRIPTOR = _EOS,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:EOS)
  ))
_sym_db.RegisterMessage(EOS)

DefaultSpecialToken = _reflection.GeneratedProtocolMessageType('DefaultSpecialToken', (_message.Message,), dict(
  DESCRIPTOR = _DEFAULTSPECIALTOKEN,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:DefaultSpecialToken)
  ))
_sym_db.RegisterMessage(DefaultSpecialToken)

CustomTokenEntry = _reflection.GeneratedProtocolMessageType('CustomTokenEntry', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMTOKENENTRY,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:CustomTokenEntry)
  ))
_sym_db.RegisterMessage(CustomTokenEntry)

ModelProto = _reflection.GeneratedProtocolMessageType('ModelProto', (_message.Message,), dict(
  DESCRIPTOR = _MODELPROTO,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:ModelProto)
  ))
_sym_db.RegisterMessage(ModelProto)


# @@protoc_insertion_point(module_scope)
