# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bmodel.proto\"\\\n\x10NormalizerConfig\x12\r\n\x05lower\x18\x01 \x01(\x08\x12\x16\n\x0eunicode_format\x18\x02 \x01(\t\x12!\n\x0c\x63ustom_rules\x18\x03 \x03(\x0b\x32\x0b.CustomRule\"2\n\nCustomRule\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12\x13\n\x0breplacement\x18\x02 \x01(\t\"z\n\rUnigramConfig\x12\x13\n\x0bmax_sub_len\x18\x01 \x01(\r\x12\x10\n\x08\x65m_iters\x18\x02 \x01(\r\x12\r\n\x05n_per\x18\x03 \x01(\x02\x12\x0f\n\x07\x65psilon\x18\x04 \x01(\x02\x12\r\n\x05\x61lpha\x18\x05 \x01(\x02\x12\x13\n\x0bunk_penalty\x18\x06 \x01(\x02\"*\n\x0bUnigramProb\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04prob\x18\x02 \x01(\x02\"(\n\nVocabEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"(\n\nTokenEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"T\n\x11SpecialTokenEntry\x12\x13\n\ttoken_str\x18\x01 \x01(\tH\x00\x12!\n\ntoken_pair\x18\x02 \x01(\x0b\x32\x0b.TokenEntryH\x00\x42\x07\n\x05token\"\xe8\x01\n\nModelProto\x12\x1a\n\x05vocab\x18\x01 \x03(\x0b\x32\x0b.VocabEntry\x12*\n\x0especial_tokens\x18\x02 \x03(\x0b\x32\x12.SpecialTokenEntry\x12%\n\nnormalizer\x18\x03 \x01(\x0b\x32\x11.NormalizerConfig\x12\x12\n\nmodel_type\x18\x04 \x01(\t\x12\x12\n\nvocab_size\x18\x05 \x01(\r\x12\x1f\n\x07unigram\x18\x06 \x01(\x0b\x32\x0e.UnigramConfig\x12\"\n\x0cunigram_prob\x18\x07 \x03(\x0b\x32\x0c.UnigramProbb\x06proto3')
)




_NORMALIZERCONFIG = _descriptor.Descriptor(
  name='NormalizerConfig',
  full_name='NormalizerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lower', full_name='NormalizerConfig.lower', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unicode_format', full_name='NormalizerConfig.unicode_format', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_rules', full_name='NormalizerConfig.custom_rules', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=107,
)


_CUSTOMRULE = _descriptor.Descriptor(
  name='CustomRule',
  full_name='CustomRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pattern', full_name='CustomRule.pattern', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='replacement', full_name='CustomRule.replacement', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=159,
)


_UNIGRAMCONFIG = _descriptor.Descriptor(
  name='UnigramConfig',
  full_name='UnigramConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_sub_len', full_name='UnigramConfig.max_sub_len', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='em_iters', full_name='UnigramConfig.em_iters', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_per', full_name='UnigramConfig.n_per', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epsilon', full_name='UnigramConfig.epsilon', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='UnigramConfig.alpha', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unk_penalty', full_name='UnigramConfig.unk_penalty', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=283,
)


_UNIGRAMPROB = _descriptor.Descriptor(
  name='UnigramProb',
  full_name='UnigramProb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='UnigramProb.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prob', full_name='UnigramProb.prob', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=327,
)


_VOCABENTRY = _descriptor.Descriptor(
  name='VocabEntry',
  full_name='VocabEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='VocabEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='VocabEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=369,
)


_TOKENENTRY = _descriptor.Descriptor(
  name='TokenEntry',
  full_name='TokenEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='TokenEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='TokenEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=411,
)


_SPECIALTOKENENTRY = _descriptor.Descriptor(
  name='SpecialTokenEntry',
  full_name='SpecialTokenEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token_str', full_name='SpecialTokenEntry.token_str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token_pair', full_name='SpecialTokenEntry.token_pair', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='token', full_name='SpecialTokenEntry.token',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=413,
  serialized_end=497,
)


_MODELPROTO = _descriptor.Descriptor(
  name='ModelProto',
  full_name='ModelProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vocab', full_name='ModelProto.vocab', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='special_tokens', full_name='ModelProto.special_tokens', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normalizer', full_name='ModelProto.normalizer', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_type', full_name='ModelProto.model_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vocab_size', full_name='ModelProto.vocab_size', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unigram', full_name='ModelProto.unigram', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unigram_prob', full_name='ModelProto.unigram_prob', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=732,
)

_NORMALIZERCONFIG.fields_by_name['custom_rules'].message_type = _CUSTOMRULE
_SPECIALTOKENENTRY.fields_by_name['token_pair'].message_type = _TOKENENTRY
_SPECIALTOKENENTRY.oneofs_by_name['token'].fields.append(
  _SPECIALTOKENENTRY.fields_by_name['token_str'])
_SPECIALTOKENENTRY.fields_by_name['token_str'].containing_oneof = _SPECIALTOKENENTRY.oneofs_by_name['token']
_SPECIALTOKENENTRY.oneofs_by_name['token'].fields.append(
  _SPECIALTOKENENTRY.fields_by_name['token_pair'])
_SPECIALTOKENENTRY.fields_by_name['token_pair'].containing_oneof = _SPECIALTOKENENTRY.oneofs_by_name['token']
_MODELPROTO.fields_by_name['vocab'].message_type = _VOCABENTRY
_MODELPROTO.fields_by_name['special_tokens'].message_type = _SPECIALTOKENENTRY
_MODELPROTO.fields_by_name['normalizer'].message_type = _NORMALIZERCONFIG
_MODELPROTO.fields_by_name['unigram'].message_type = _UNIGRAMCONFIG
_MODELPROTO.fields_by_name['unigram_prob'].message_type = _UNIGRAMPROB
DESCRIPTOR.message_types_by_name['NormalizerConfig'] = _NORMALIZERCONFIG
DESCRIPTOR.message_types_by_name['CustomRule'] = _CUSTOMRULE
DESCRIPTOR.message_types_by_name['UnigramConfig'] = _UNIGRAMCONFIG
DESCRIPTOR.message_types_by_name['UnigramProb'] = _UNIGRAMPROB
DESCRIPTOR.message_types_by_name['VocabEntry'] = _VOCABENTRY
DESCRIPTOR.message_types_by_name['TokenEntry'] = _TOKENENTRY
DESCRIPTOR.message_types_by_name['SpecialTokenEntry'] = _SPECIALTOKENENTRY
DESCRIPTOR.message_types_by_name['ModelProto'] = _MODELPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NormalizerConfig = _reflection.GeneratedProtocolMessageType('NormalizerConfig', (_message.Message,), dict(
  DESCRIPTOR = _NORMALIZERCONFIG,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:NormalizerConfig)
  ))
_sym_db.RegisterMessage(NormalizerConfig)

CustomRule = _reflection.GeneratedProtocolMessageType('CustomRule', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMRULE,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:CustomRule)
  ))
_sym_db.RegisterMessage(CustomRule)

UnigramConfig = _reflection.GeneratedProtocolMessageType('UnigramConfig', (_message.Message,), dict(
  DESCRIPTOR = _UNIGRAMCONFIG,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:UnigramConfig)
  ))
_sym_db.RegisterMessage(UnigramConfig)

UnigramProb = _reflection.GeneratedProtocolMessageType('UnigramProb', (_message.Message,), dict(
  DESCRIPTOR = _UNIGRAMPROB,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:UnigramProb)
  ))
_sym_db.RegisterMessage(UnigramProb)

VocabEntry = _reflection.GeneratedProtocolMessageType('VocabEntry', (_message.Message,), dict(
  DESCRIPTOR = _VOCABENTRY,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:VocabEntry)
  ))
_sym_db.RegisterMessage(VocabEntry)

TokenEntry = _reflection.GeneratedProtocolMessageType('TokenEntry', (_message.Message,), dict(
  DESCRIPTOR = _TOKENENTRY,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:TokenEntry)
  ))
_sym_db.RegisterMessage(TokenEntry)

SpecialTokenEntry = _reflection.GeneratedProtocolMessageType('SpecialTokenEntry', (_message.Message,), dict(
  DESCRIPTOR = _SPECIALTOKENENTRY,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:SpecialTokenEntry)
  ))
_sym_db.RegisterMessage(SpecialTokenEntry)

ModelProto = _reflection.GeneratedProtocolMessageType('ModelProto', (_message.Message,), dict(
  DESCRIPTOR = _MODELPROTO,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:ModelProto)
  ))
_sym_db.RegisterMessage(ModelProto)


# @@protoc_insertion_point(module_scope)
